language: php

php:
    - 7.1
    - 7.2
    - 7.3

env:
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.4.*
    - SYMFONY_VERSION=5.0.*

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer update --prefer-dist

script:
    - composer validate --strict

    - vendor/bin/behat --strict -vvv --no-interaction
